services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: next-payload-app
    restart: always
    ports:
      - '4000:4000'
    env_file:
      - .env
    depends_on:
      - postgres
    environment:
      NODE_ENV: production

  postgres:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: cosmo
      POSTGRES_PASSWORD: qwerty666
      POSTGRES_DB: rizky-p-mahendra-db

volumes:
  pgdata:
